server:
  port: 8081

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect # H2 preferable due to compatibility issue of derby with SB 3.1.0 release
  datasource:
    url: jdbc:h2:mem:interstellar
    driver-class-name: org.h2.Driver
    name: sa
    password: password